### ISSUE TITLE
Website link raises a security warning

### ISSUE THREAD

**Issue by arabelladonna** [Limvot/kraken#5]
The website linked in the readme raises a security warning.

**Comment by Limvot** [comment]
It does, sorry! I should remove the link until I set it up again. It's not actually dangerous, but I don't have the website running on my VPS right now, so it's serving my matrix homeserver instead, which has a different cert.

I'm gratified by your interest in the language, but it's not in a very usable state right now - hopefully you can get it compiling if you want in that other issue, but it's definitely not nice to use! Kraken is my long and oft-interrupted journey to build the best programming language I can, and I'm actually in the opening-ish stages of my 3.5th rewrite with some fun new ideas (basing it on a kraken-prime minimal lisp, bringing back in Agol/C/Rust style syntax using macros backed by a full GLL parser, optimization using value state dependence graphs (VSDGs)). I've recently started a PhD program and will hopefully be able to have Kraken be a part of my thesis work in a few years, and after some major life events I've settled down a bit to where I can devote at least a bit of serious work to Kraken again. If you want to see the current state, I worked out a basic lisp by following the Make-A-Lisp (MAL) tutorial using Kraken as the implementation language, which is at top level in mal.krak, and I'm working on integrating a GLL parser I'm writing in fungll.krak.

Anyway, all that to say, this definitely isn't dead, but it'll be a few months  before it's interesting to others, and years before it's actually useful ;D The rewrites always take longer than expected...

**Comment by Limvot** [comment]
Last week I made a new minimalist website that explains what I'm trying and has an emscripten-compiled try-it-online feature.
