### ISSUE TITLE
Sample code only runs when passed no_compile

### ISSUE THREAD

**Issue by lotusronin** [Limvot/kraken#7]
Running
`rm *.wasm; chez --script ./partial_eval.scm find.kp && wasmtime csc_out.wasm`
will result in the error
`Exception in cdr: () is not a pair`

but when it is run with no_compile runs without issue.
[sample.zip](https://github.com/Limvot/kraken/files/8527151/sample.zip)

**Comment by Limvot** [comment]
Fixed! Thank you for the new testcase and bug report - not entirely sure why, but this exercised a codepath in the partial eval implementation of cond that wasn't being run and had multiple bugs.
